name: CI

on:
  pull_request:
    branches: ['master', 'main']
  push:
    branches: ['master', 'main']
  workflow_dispatch:

jobs:
  create-project:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Install falco
        run: uv tool install "falco-cli[just,hatch]"
      - name: Checkout Code Repository
        uses: actions/checkout@v4
      # - name: Debugging with ssh
      #   uses: lhotari/action-upterm@v1
      - name: Generate a project
        run: falco start-project test-project -b . --skip-new-version-check
        working-directory: ./
      - name: Run django checks
        run: cd test_project && just dj check --fail-level WARNING

  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Install falco
        run: uv tool install "falco-cli[just,hatch]"
      - name: Checkout Code Repository
        uses: actions/checkout@v4
      - name: Generate a project
        run: falco start-project test-project -b . --skip-new-version-check
        working-directory: ./
      - name: Generate requirements.txt
        run: cd test_project && just bootstrap
      - name: Build image
        run: cd test_project && rm .env && docker build . -f deploy/Dockerfile


